# models.py
"""Pydantic models and LangGraph state schema for the Curriculum Engine.

Defines:
- CurriculumRequest: user's input (topic, level, preferences)
- CurriculumPlan: the structured curriculum plan from the planning agent
- GeneratedArtifact: a generated content piece (lesson, exercises, or assessment)
- CurriculumEngineState: the TypedDict flowing through the LangGraph workflow

Key concepts demonstrated:
- TypedDict state for a non-conversational, multi-stage pipeline
- Each field is written by exactly one node — no reducers needed
- Pydantic models for validation, TypedDict for LangGraph state
"""

from typing import Literal

from pydantic import BaseModel, Field
from typing_extensions import TypedDict

# Valid CEFR levels for English proficiency
CEFR_LEVELS = ("A1", "A2", "B1", "B2", "C1", "C2")


class CurriculumRequest(BaseModel):
    """User's request to generate a curriculum module."""

    topic: str = Field(description="The topic to cover (e.g., 'Business English for meetings')")
    level: Literal["A1", "A2", "B1", "B2", "C1", "C2"] = Field(
        description="Target CEFR proficiency level"
    )
    preferences: dict = Field(
        default_factory=dict,
        description="Optional preferences: teaching_style, focus_areas, etc.",
    )


class CurriculumPlan(BaseModel):
    """Structured curriculum plan produced by the planning agent."""

    title: str = Field(description="Module title")
    description: str = Field(description="Brief module description")
    lesson_outline: str = Field(description="What the lesson should cover")
    exercise_types: list[str] = Field(description="Types of exercises to include")
    assessment_approach: str = Field(description="How the assessment should be structured")


class GeneratedArtifact(BaseModel):
    """A content artifact generated by a DeepAgents sub-agent."""

    content: str = Field(description="The generated markdown content")
    artifact_type: Literal["lesson", "exercises", "assessment"] = Field(
        description="What kind of artifact this is"
    )
    agent_todos: list[dict] = Field(
        default_factory=list,
        description="The agent's TodoList showing its planning process",
    )


class CurriculumEngineState(TypedDict):
    """State schema for the curriculum engine StateGraph.

    This is a pipeline state (not conversational), so we use a plain
    TypedDict instead of MessagesState. Each field maps to a specific
    node in the graph.

    DeepAgents concept: the outer LangGraph state holds the workflow
    data, while each DeepAgent manages its own internal state (TodoList,
    working files) independently.
    """

    # -- Input (set at invocation) --
    curriculum_request: dict          # CurriculumRequest as dict

    # -- After plan_curriculum --
    curriculum_plan: dict | None      # CurriculumPlan as dict
    plan_feedback: str                # Moderator feedback on plan (empty = approved)

    # -- After generate_lesson --
    lesson: dict | None               # GeneratedArtifact as dict
    lesson_feedback: str              # Moderator feedback on lesson

    # -- After generate_exercises --
    exercises: dict | None            # GeneratedArtifact as dict
    exercises_feedback: str           # Moderator feedback on exercises

    # -- After generate_assessment --
    assessment: dict | None           # GeneratedArtifact as dict
    assessment_feedback: str          # Moderator feedback on assessment

    # -- After assemble_module --
    assembled_module: str | None      # Final assembled markdown

    # -- Workflow tracking --
    current_step: str                 # Current step name for UI progress display
